server:
  port: 9090 # 端口
logging:
  file:
    path: /app/log
  level:
    root: INFO
spring:
  datasource:
    url: jdbc:mysql://rm-uf6tpisqevjobg5o4.mysql.rds.aliyuncs.com:3306/todolist?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: todolist
    password: Aliyun@liu5689
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5